name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Copy existing build
        run: |
          if [ -d "out" ]; then
            echo "Using existing 'out' directory"
          else
            echo "No 'out' directory found, attempting build"
            npm run build || echo "Build failed, but continuing to use any existing static files"
          fi
          
      - name: Touch .nojekyll
        run: |
          mkdir -p out
          touch out/.nojekyll
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true